services:
  - type: web
    name: crm-backend
    env: node
    repo: https://github.com/DMHCAIT/crm-backend.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false  
      - key: JWT_SECRET
        generateValue: true